/** Fallback list when `/api/kth-programmes` is unavailable. Snapshot of KOPPS programme titles. */
export const studyPrograms = [
  "Bachelor's Programme in Business  Engineering",
  "Bachelor's Programme in Information and Communication Technology",
  "Bachelor's Programme in Medical Informatics",
  "Bachelor's Programme in Property Development and Agency",
  "Bachelor's Programme in Real Estate and Finance",
  "Bachelor's Programme in Simulation Technology and Virtual Design",
  "Basic Study Programme for Natural Science Studies",
  "Bridging programme for architects with foreign qualifications",
  "Bridging programme for engineers with foreign qualifications",
  "Bridging Teacher Education Programme",
  "Bridging Teacher Education Programme in Mathematics, Science and Technology for Graduates with a Third Cycle Degree",
  "Degree Progr. in Civil Engineering",
  "Degree Progr. in Construction Management",
  "Degree Progr. Open Entrance",
  "Degree Programme in Architecture",
  "Degree Programme in Biotechnology",
  "Degree Programme in Business IT Engineering",
  "Degree Programme in Chemical Engineering",
  "Degree Programme in Chemical Science and Engineering",
  "Degree Programme in Chemistry and Chemical Engineering",
  "Degree Programme in Civil Engineering and Urban Management",
  "Degree Programme in Computer Engineering",
  "Degree Programme in Computer Engineering and Economics",
  "Degree Programme in Computer Engineering and Electronics",
  "Degree Programme in Computer Engineering and Health",
  "Degree Programme in Computer Science and Engineering",
  "Degree Programme in Constructional Engineering",
  "Degree Programme in Constructional Engineering and Design",
  "Degree Programme in Constructional Engineering and Economics",
  "Degree Programme in Constructional Engineering and Health",
  "Degree Programme in Design and Product Realisation",
  "Degree Programme in Electrical Engineering",
  "Degree Programme in Electrical Engineering and Economics",
  "Degree Programme in Electrical Engineering and Health",
  "Degree Programme in Electronics and Communication Engineering",
  "Degree Programme in Electronics and Computer Engineering",
  "Degree Programme in Energy and Environment",
  "Degree Programme in Engineering and Economics",
  "Degree Programme in Engineering Chemistry",
  "Degree Programme in Engineering Chemistry, Mid Sweden University – KTH",
  "Degree Programme in Engineering Mathematics",
  "Degree Programme in Engineering Physics",
  "Degree Programme in ICT Engineering",
  "Degree Programme in Industrial Engineering",
  "Degree Programme in Industrial Engineering and Management",
  "Degree Programme in Industrial Technology and Production Maintenance",
  "Degree Programme in Industrial Technology and Sustainability",
  "Degree Programme in Information and Communication Technology",
  "Degree Programme in Information Systems",
  "Degree Programme in IT Engineering",
  "Degree Programme in Materials Design and Engineering",
  "Degree Programme in Materials Engineering",
  "Degree Programme in Mechanical Engineering",
  "Degree Programme in Mechanical Engineering and Economics",
  "Degree Programme in Mechanical Engineering and Health",
  "Degree Programme in Mechanical Engineering, Innovation and Design",
  "Degree Programme in Mechatronics and Industrial IT Engineering",
  "Degree Programme in Media Technology",
  "Degree Programme in Medical Engineering",
  "Degree Programme in Medical Technology",
  "Degree Programme in Microelectronics",
  "Degree Programme in Surveying",
  "Degree Programme in Technology and Health",
  "Degree Programme in Vehicle Engineering",
  "Degree Programme Open Entrance",
  "Graduate School of Urban Studies",
  "Individual Study Programme",
  "Master (Two Years), Erasmus Mundus, Industrial Management",
  "Master of Science in Engineering and in Education",
  "Master of Science in Engineering and of Education",
  "Master's Programme,  Architectural Lighting Design",
  "Master's Programme,  ICT Entrepreneurship, 90 credits",
  "Master's Programme, Aerospace Engineering",
  "Master's Programme, Applied and Computational Mathematics",
  "Master's Programme, Applied and Engineering Mathematics",
  "Master's Programme, Applied Information Technology, 90 credits",
  "Master's Programme, Applied Logistics",
  "Master's Programme, Applied Physics",
  "Master's Programme, Architectural Engineering",
  "Master's Programme, Architectural Lighting Design and Health",
  "Master's Programme, Architecture",
  "Master's Programme, Banking and Finance",
  "Master's Programme, Biological Physics, 90 credits",
  "Master's Programme, Biomedical Materials",
  "Master's Programme, Biostatistics and Data Science",
  "Master's Programme, Biotechnology",
  "Master's Programme, Buildings and Building Services, 90 credits",
  "Master's Programme, Chemical Engineering for Energy and Environment",
  "Master's Programme, Chemical Engineering, 90 credits",
  "Master's Programme, Chemical Science and Engineering",
  "Master's Programme, Civil and Architectural Engineering",
  "Master's Programme, Communication Systems",
  "Master's Programme, Computational and Systems Biology",
  "Master's Programme, Computational Chemistry and Computational Physics",
  "Master's Programme, Computer Networks",
  "Master's Programme, Computer Networks, 90 credits",
  "Master's Programme, Computer Science",
  "Master's Programme, Computer Science, 90 credits",
  "Master's Programme, Computer Simulations for Science and Engineering",
  "Master's Programme, Cybersecurity",
  "Master's Programme, Data-driven Health",
  "Master's Programme, Decentralized Smart Energy Systems",
  "Master's Programme, Design and Building, 90 credits",
  "Master's Programme, Design and Implementation of ICT Products and Systems",
  "Master's Programme, Distributed Computing",
  "Master's Programme, Economics of Innovation and Growth",
  "Master's Programme, Economics of Innovation and Growth, 90 credits",
  "Master's Programme, Electric Power Engineering",
  "Master's Programme, Electric Power Engineering, 90 credits",
  "Master's Programme, Electromagnetics, Fusion and Space Engineering",
  "Master's Programme, Electrophysics",
  "Master's Programme, Embedded Systems",
  "Master's Programme, Energy Innovation",
  "Master's Programme, Engineering and Management of Information Systems",
  "Master's Programme, Engineering and Management of Information Systems, 90 credits",
  "Master's Programme, Engineering Design",
  "Master's Programme, Engineering Materials Science",
  "Master's Programme, Engineering Mechanics",
  "Master's Programme, Engineering Mechanics, 90 credits",
  "Master's Programme, Engineering Physics",
  "Master's Programme, Entrepreneurship and Innovation Management",
  "Master's Programme, Environmental Engineering",
  "Master's Programme, Environmental Engineering and Sustainable Infrastructure",
  "Master's Programme, Environmental Engineering and Sustainable Infrastructure, 90 hp",
  "Master's Programme, Environomical Pathways for Sustainable Energy Systems",
  "Master's Programme, Ergonomics and Human-Technology-Organisation",
  "Master's Programme, Geodesy and Geoinformatics",
  "Master's Programme, Geodesy and Geoinformatics, 90 credits",
  "Master's Programme, Human-Computer Interaction",
  "Master's Programme, Human-Computer Interaction, 90 credits",
  "Master's Programme, ICT Entrepreneurship",
  "Master's Programme, ICT Innovation",
  "Master's Programme, Industrial and Environmental Biotechnology",
  "Master's Programme, Industrial Ecology, 90 credits",
  "Master's Programme, Industrial Engineering and Management",
  "Master's Programme, Industrial Management",
  "Master's Programme, Industrial Management, 90 credits",
  "Master's Programme, Information and Communication Systems Security",
  "Master's Programme, Information and Communication Systems Security, 90 credits",
  "Master's Programme, Information and Network Engineering",
  "Master's Programme, Infrastructure Engineering",
  "Master's Programme, Innovative Sustainable Energy Engineering",
  "Master's Programme, Innovative Technology for Healthy Living",
  "Master's Programme, Integrated Product Design",
  "Master's Programme, Interactive Media Technology",
  "Master's Programme, Interactive Systems Engineering",
  "Master's Programme, Interactive Systems Engineering, 90 credits",
  "Master's Programme, Internetworking",
  "Master's Programme, Internetworking, 90 credits",
  "Master's Programme, Land Law and Property Development, 90 credits",
  "Master's Programme, Land Management, 120 credits",
  "Master's Programme, Land Management, 90 credits",
  "Master's Programme, Machine Design",
  "Master's Programme, Machine Learning",
  "Master's Programme, Macromolecular Materials",
  "Master's Programme, Management and Engineering of Environment and Energy",
  "Master's Programme, Maritime Engineering",
  "Master's Programme, Material Chemistry, 90 credits",
  "Master's Programme, Materials and Sensors System for Environmental Technologies",
  "Master's Programme, Materials Processing, 90 credits",
  "Master's Programme, Materials Science and Engineering",
  "Master's Programme, Mathematics",
  "Master's Programme, Mechatronics",
  "Master's Programme, Media Management",
  "Master's Programme, Media Technology",
  "Master's Programme, Medical Biotechnology",
  "Master's Programme, Medical Engineering",
  "Master's Programme, Medical Engineering, 90 credits",
  "Master's Programme, Medical Imaging",
  "Master's Programme, Modern Physics",
  "Master's Programme, Molecular Design, 90 credits",
  "Master's Programme, Molecular Science and Engineering",
  "Master's Programme, Molecular Techniques in Life Science",
  "Master's Programme, Nanoelectronics, 90 credits",
  "Master's Programme, Nanomaterials and Nanotechnology, 90 credits",
  "Master's Programme, Nanotechnology",
  "Master's Programme, Naval Architecture",
  "Master's Programme, Network Services and Systems",
  "Master's Programme, Nuclear Energy Engineering",
  "Master's Programme, Nuclear Fusion Science and Engineering Physics",
  "Master's Programme, Pharmaceutical Engineering, 90 credits",
  "Master's Programme, Pharmaceuticals and Pharmaceutical Engineering",
  "Master's Programme, Philosophy of Science and Technology",
  "Master's Programme, Philosophy of Science and Technology, 90 credits",
  "Master's Programme, Photonics",
  "Master's Programme, Photonics, 90 credits",
  "Master's Programme, Product Realisation",
  "Master's Programme, Production Engineering and Management",
  "Master's Programme, Production Engineering and Management, 90 credits",
  "Master's Programme, Project Management and Operational Development",
  "Master's Programme, Pulp and Paper Chemistry and Technology, 90 credits",
  "Master's Programme, Quantum Physics, 90 credits",
  "Master's Programme, Railway Engineering",
  "Master's Programme, Real Estate",
  "Master's Programme, Real Estate and Construction Management",
  "Master's Programme, Real Estate Development and Financial Services",
  "Master's Programme, Real Estate Management",
  "Master's Programme, Real Estate Management, 60 credits",
  "Master's Programme, Real Estate Management, 90 credits",
  "Master's Programme, Research on Information and Communication Technologies",
  "Master's Programme, Scientific Computing",
  "Master's Programme, Scientific Computing, 90 credits",
  "Master's Programme, Security and Mobile Computing",
  "Master's Programme, Smart Electrical Networks and Systems",
  "Master's Programme, Software Engineering",
  "Master's Programme, Software Engineering of Distributed Systems",
  "Master's Programme, Software Engineering of Distributed Systems, 90 credits",
  "Master's Programme, Sound and Vibration",
  "Master's Programme, Sound and Vibration, 90 credits",
  "Master's Programme, Spatial Planning",
  "Master's Programme, Spatial Planning, 90 credits",
  "Master's Programme, Sports Technology",
  "Master's Programme, Sustainable Digitalisation",
  "Master's Programme, Sustainable Energy Engineering",
  "Master's Programme, Sustainable Energy Engineering, 90 credits",
  "Master's Programme, Sustainable Production Development",
  "Master's Programme, Sustainable Technology",
  "Master's Programme, Sustainable Technology, 90 credits",
  "Master's Programme, Sustainable Urban Planning and Design",
  "Master's Programme, Sustainable Urban Transition",
  "Master's Programme, System-on-Chip Design",
  "Master's Programme, System-on-Chip Design, 90 credits",
  "Master's Programme, Systems Biology",
  "Master's Programme, Systems, Control and Robotics",
  "Master's Programme, Technology, Health and Work Environment Development",
  "Master's Programme, Technology, Work and Health",
  "Master's Programme, Technology-based Entrepreneurship",
  "Master's Programme, Transport and Geoinformation Technology",
  "Master's Programme, Transport Systems",
  "Master's Programme, Transport, Mobility and Innovation",
  "Master's Programme, Turbomachinery Aeromechanic University Training",
  "Master's Programme, Urban Development and Design",
  "Master's Programme, Urban Planning and Design",
  "Master's Programme, Urbanism Studies",
  "Master's Programme, Vehicle Engineering",
  "Master's Programme, Water System Technology",
  "Master's Programme, Wireless Systems",
  "Master's Programme, Wireless Systems, 90 credits",
  "School of Aeronautical Engineering",
  "School of Aircraft Operations & Maintenance Eng. Lower level",
  "School of Chemical Engineering, Lower level",
  "School of Chemical Engineering, MH",
  "School of Civil Engineering, HDA",
  "School of Construction Industry, Lower level",
  "School of Constructional Engineering, Lower Level",
  "School of Constructional Technology",
  "School of Constructional Technology and Real Estate",
  "School of Constructional Technology and Real Estate Agency",
  "School of Constructional Technology, Lower level",
  "School of Control and Maintenance Engineering, Lower level",
  "School of Control and Maintenance Technology, Lower level",
  "School of Electrical Engineering, Lower level",
  "School of Electrical Engineering, MDH",
  "School of Electronics and Computer Science 40 p, Lower level",
  "School of Electronics and Computer Science 80 p, Lower level",
  "School of Engineering Industry, Lower level",
  "School of Graphic Industry, Lower level",
  "School of Graphic Technology",
  "School of Manufacturing Technology",
  "School of Mechanical Engineering and Electronics Lower level",
  "School of Mechanical Engineering, Lower level",
  "School of Mechanical Engineering, MDH",
  "School of Mechanical Engineering, MH",
  "School of Metallurgy and Materials Technology",
  "School of Surveying, HiG",
  "School of Telecommunication and Computer Science Lower level",
  "School of Vehicle Engineering, MH",
  "Subject Teacher Education in Technology, Secondary Education",
  "Supplementary Education as Subject Teacher in Secondary Education",
  "Supplementary Education in Constructional Engineering",
  "Supplementary Education in Electrical Engineering",
  "Supplementary Education in Electrical or Mechanical Engineering",
  "Supplementary Education in Mechanical Engineering",
  "Technical Preparatory Semester",
  "Technical Preparatory Semester, Constructional Eng Studies",
  "Technical Preparatory Semester, Electrical Eng Studies",
  "Technical Preparatory Semester, Mechanical Eng Studies",
  "Technical Preparatory Year",
  "Technical Preparatory Year towards Bachelor of Science in Engineering, online with meetings on campus",
  "Technical Preparatory Year, online with meetings on campus",
];
